name: 'Terraform'

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    env:
      # AWS secrets
      #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEVOPS_ACCESS_KEY_ID }}
      #AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_DEVOPS_SECRET_ACCESS_KEY }}

      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACESS_KEY }}

       

    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.3
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        #args: '-var="instance_type=t2.medium"'
    
    - name: Terraform plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.3
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
       # args: '-var="instance_type=t2.medium"'
      
    - name: Terraform apply
      #if: ${{ github.event.inputs.terraform_action == 'apply' }}
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.3
        #tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: '.'
        tf_actions_comment: true
        #args: '-auto-approve -var="instance_type=t2.medium"'
    
   # - name: Terraform destroy
   #   if: ${{ github.event.inputs.terraform_action == 'destroy' }}
   #   uses: hashicorp/terraform-github-actions@master
   #   with:
    #    tf_actions_version: 0.14.3
    #    tf_actions_subcommand: ${{ github.event.inputs.terraform_action }}
    #    tf_actions_working_dir: '.'
     #   tf_actions_comment: true
    #    args: '-auto-approve -var="instance_type=t2.medium"'